config/routes.rb
MeasuringWellness::Application.routes.draw do
	resources :users
	resources :sessions, only: [ :new, :create, :destroy ]
	resources :orders
	resources :recommendations, except: [ :new ]	

	resources :coupons, only: [ :new, :create, :destroy ], path: '/admin/coupon'
	resources :analytes, path: '/admin/analyte'
	resources :analyte_groups, path: '/admin/analyte_group'
	resources :rules, path: '/admin/rule'
	resources :thresholds, path: '/admin/threshold'
	resources :results, path: '/admin/result'
	resources :tests, path: '/admin/test'
	
	resources :flags, path: '/admin/flag'
	resources :recommendations, path: 'admin/recommendation'
	resources :evaluations, path: 'admin/evaluation', 
		except: [ :index ]
	resources :consultations, path: 'admin/consultation', 
		only: [ :edit, :update, :destroy ]

 	root 'home_pages#index'	
 
	match '/signup', 				to: 'users#new', 					via: 'get'
	match '/signup',				to: 'users#create',				via: 'post'
	match '/terms_of_use',	to: 'users#terms_of_use', via: 'get'
	match '/terms_of_use',	to: 'users#terms_of_use',	via: 'patch'
	match '/signin',				to: 'sessions#new', 			via: 'get'
	match '/signin', 				to: 'sessions#create', 		via: 'post'
	match '/signout',				to:	'sessions#destroy',		via: 'delete'

	match '/measures', 			to: 'home_pages#measures', 			via: 'get'
 	match '/homeostasis', 	to: 'home_pages#homeostasis', 	via: 'get'
 	match '/science', 			to: 'home_pages#science', 			via: 'get'

	match '/users/:id/profile',	to: 'users#profile',	via: 'get', as: 'profile'
	match '/consultation/:id', to: 'consultations#show', 
		via: 'get', as: 'user_consultation'

	match '/admin', to: 'admin#home', via: 'get'
	match '/admin/orders', to: 'admin#orders', via: 'get'
	match '/admin/users', to: 'admin#users', via: 'get'
	match '/admin/test/:id/evaluate', to: 'tests#evaluate', via: 'post'

  

end

app/models/analyte.rb
class Analyte < ActiveRecord::Base
	include Partitions

	# Callbacks
	serialize :partitions
	after_initialize :initialize_partitions
	before_save { self.partitions = PartitionCollection.new self.partitions }

	# Relations
	has_many :rules
	has_many :analytes

	# Validations
	validates :name, presence: true

end

app/controllers/analytes_controller.rb
class AnalytesController < ApplicationController
	before_action :must_be_admin
	
	def index
		@analytes = Analyte.all
	end

	def show
		@analyte = Analyte.find params[:id]
		@rules = @analyte.rules
	end

	def new
		@analyte = Analyte.new
	end

	def create
		@analyte = Analyte.new analyte_params
		@analyte.partitions = [] # Reset partitions for clean slate
		params[:analyte][:partitions].each do |part|
			@analyte.create_partition(
				part[:severity].to_i, 
				resolve_threshold( part[:threshold] ), 
				part[:weight].to_f
			) unless (
				part[:severity].blank? && part[:threshold].blank? && part[:weight].blank?
			)
		end

		# Add Partition
		if params[:add_partition]
			@analyte.create_partition
			render :new
			return
		end

		if @analyte.save
			flash[:success] = "Analyte created!"
			redirect_to analytes_path

		else
			flash.now[:error] = 'There was an error creating the analyte'
			render :new
		
		end
	end

	def edit
		@analyte = Analyte.find params[:id]
	end

	def update
		@analyte = Analyte.find params[:id]

		@analyte.update_attributes analyte_params
		@analyte.partitions = []
		params[:analyte][:partitions].each do |part|
			@analyte.create_partition(
				part[:severity].to_i, 
				resolve_threshold( part[:threshold] ), 
				part[:weight].to_f
			) unless (
				part[:severity].blank? && part[:threshold].blank? && part[:weight].blank?
			)
		end

		if params[:add_partition]
			@analyte.create_partition
			render :edit
			return
		end
	
		if @analyte.save
			flash[:success] = "Analyte updated!"
			redirect_to analyte_path( @analyte )

		else
			flash.now[:error] = 'There was an error updating the Analyte'
			render :edit
		
		end

	end

	def destroy
		analyte = Analyte.find params[:id]
		analyte.destroy

		flash[:success] = "Analyte destroyed!"
		redirect_to analytes_path
	end

	private

		def analyte_params
			params.require(:analyte).permit :name
		end
		
		def resolve_threshold( str )
			return Float::INFINITY if str.downcase == 'infinity'
			str.to_f
		end
end

app/helpers/analytes_helper.rb
module AnalytesHelper
end

app/views/analytes/_analyte_form.html.erb
<%= form_for analyte do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<h2>Partitions</h2>
	<table>
		<thead>
			<th>Severity</th>
			<th>Threshold</th>
			<th>Weight</th>
		</thead>
		<tbody>
			<% analyte.partitions.each do |part| %>
				<tr>
					<%= f.fields_for 'partitions', part, index: nil do |pf| %>
						<td><%= pf.text_field :severity %></td>
						<td><%= pf.text_field :threshold %></td>
						<td><%= pf.text_field :weight %></td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>

	<%= submit_tag  "Add Partition", name: :add_partition %>

	<%= f.submit %>
<% end %>

app/views/analytes/_rules_table.html.erb
<table class='rules-table'>
	<thead>
		<th>Group</th>
		<th>Weight</th>
		<th>Parititons</th>
	</thead>
	<tbody>
		<% rules.each do |rule| %>
			<tr class='rule'>
				<td class='analyte-group'>
					<%= link_to rule.analyte_group.name, 
						analyte_group_path( rule.analyte_group ) %>
				</td>
				<td class='weight'>
					<%= rule.weight %>
				</td>
				<td class='partitions'>
					<%= render partial: 'shared/partitions_table', object: rule.partitions,
						as: :partitions %>
					</td>
					<td>
						<%= link_to 'Edit', edit_rule_path( rule )%>
					</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/analytes/edit.html.erb
<h1>Edit Analyte</h1>
<%= render 'shared/flash' %>

<h2><%= @analyte.name %></h2>
<%= render partial: 'analyte_form', object: @analyte, as: :analyte %>

<%= link_to 'Cancel', analyte_path( @analyte ) %>

app/views/analytes/index.html.erb
<h1>Analytes</h1>
<%= link_to 'Admin', admin_path %>
<%= render 'shared/flash' %>

<%= link_to "New Analyte", new_analyte_path %>

<ul id="analytes">
	<% @analytes.each do |analyte| %>		
		<li class="analyte">
			<span class="analyte-name">
				<%= link_to analyte.name, analyte %>
			</span>
		</li>
	<% end %>
</ul>

</div>

app/views/analytes/new.html.erb
<h1>Create Analyte</h1>
<%= render 'shared/flash' %>

<%= render partial: 'analyte_form', object: @analyte, as: :analyte %>
<%= link_to 'Cancel', analytes_path %>

app/views/analytes/show.html.erb
<h1>Analyte</h1>
<%= link_to 'All Analytes', analytes_path %>

<h2><%= @analyte.name %></h2>

<table>
	<thead>
		<th>Severity</th>
		<th>Threshold</th>
		<th>Weight</th>
	</thead>
	<tbody>
		<% @analyte.partitions.each do |part| %>
			<tr>
				<td><%= part.severity %></td>
				<td><%= part.threshold %></td>
				<td><%= part.weight %></td>
			</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'Edit', edit_analyte_path( @analyte ) %>

<h3>Rules</h3>
<%= render partial: 'rules_table', object: @rules, as: :rules  %>
<%= link_to 'Add Rule', new_rule_path( analyte: @analyte ) %>

<%= link_to 'Delete', @analyte, method: :delete,
	confirm: "Are you sure you want to delete this Analyte?" %>