config/routes.rb
MeasuringWellness::Application.routes.draw do
	resources :users
	resources :sessions, only: [ :new, :create, :destroy ]
	resources :orders
	resources :recommendations, except: [ :new ]	

	resources :coupons, only: [ :new, :create, :destroy ], path: '/admin/coupon'
	resources :analytes, path: '/admin/analyte'
	resources :analyte_groups, path: '/admin/analyte_group'
	resources :rules, path: '/admin/rule'
	resources :thresholds, path: '/admin/threshold'
	resources :results, path: '/admin/result'
	resources :tests, path: '/admin/test'
	
	resources :flags, path: '/admin/flag'
	resources :recommendations, path: 'admin/recommendation'
	resources :evaluations, path: 'admin/evaluation', 
		except: [ :index ]
	resources :consultations, path: 'admin/consultation', 
		only: [ :edit, :update, :destroy ]

 	root 'home_pages#index'	
 
	match '/signup', 				to: 'users#new', 					via: 'get'
	match '/signup',				to: 'users#create',				via: 'post'
	match '/terms_of_use',	to: 'users#terms_of_use', via: 'get'
	match '/terms_of_use',	to: 'users#terms_of_use',	via: 'patch'
	match '/signin',				to: 'sessions#new', 			via: 'get'
	match '/signin', 				to: 'sessions#create', 		via: 'post'
	match '/signout',				to:	'sessions#destroy',		via: 'delete'

	match '/measures', 			to: 'home_pages#measures', 			via: 'get'
 	match '/homeostasis', 	to: 'home_pages#homeostasis', 	via: 'get'
 	match '/science', 			to: 'home_pages#science', 			via: 'get'

	match '/users/:id/profile',	to: 'users#profile',	via: 'get', as: 'profile'
	match '/consultation/:id', to: 'consultations#show', 
		via: 'get', as: 'user_consultation'

	match '/admin', to: 'admin#home', via: 'get'
	match '/admin/orders', to: 'admin#orders', via: 'get'
	match '/admin/users', to: 'admin#users', via: 'get'
	match '/admin/test/:id/evaluate', to: 'tests#evaluate', via: 'post'

  

end

app/views/admin/home.html.erb
<h1>Admin</h1>
<section>
	<%= link_to 'Users', admin_users_path %> | 
	<%= link_to 'Orders', admin_orders_path %> | 
	<%= link_to 'Analytes', analytes_path %> | 
	<%= link_to 'Analyte Groups', analyte_groups_path %> | 
	<%= link_to 'Rules', rules_path %> | 
	<%#= link_to 'Results', results_path %>
	<%= link_to 'Tests', tests_path %>
</section>
<section>
	<%= link_to 'Flags', flags_path %> | 
	<%= link_to 'Recommendations', recommendations_path %>
</section>

app/views/admin/orders.html.erb
<h2>Orders</h2>
<%= link_to "Admin", admin_path %>

<div id='redemption-codes'>
	<h3>Redemption Codes</h3>	
	<%= render @coupons %>
	<section id='add-coupon'>
		<%= link_to 'New Coupon', new_coupon_path %>
	</section>
</div>

app/views/admin/users.html.erb
<h1>Users Admin</h1>

<table>
	<thead>
		<th></th>
		<th></th>
		<th>Roles</th>
	</thead>
	<tbody>
		<% @users.each do |user| %>
			<tr class='user'>
				<td class='user-name'><%= user.name %></td>
				<td class='user-email'><%= user.email %></td>
				<td class='user-roles'><%= user.roles %></td>
	<!-- 	<td class='user-actions'>
					<%= form_for user, controller: :users, action: :update do |f| %>
						<% f.hidden_field :id %>
						<% f.select :roles, ['Normal', 'Admin'] %>
					<% end %>
	-->
				</td>
			</tr>
		<% end %>
	</tbody>
</table>