config/routes.rb
MeasuringWellness::Application.routes.draw do
	resources :users
	resources :sessions, only: [ :new, :create, :destroy ]
	resources :orders
	resources :recommendations, except: [ :new ]	

	resources :coupons, only: [ :new, :create, :destroy ], path: '/admin/coupon'
	resources :analytes, path: '/admin/analyte'
	resources :analyte_groups, path: '/admin/analyte_group'
	resources :rules, path: '/admin/rule'
	resources :thresholds, path: '/admin/threshold'
	resources :results, path: '/admin/result'
	resources :tests, path: '/admin/test'
	
	resources :flags, path: '/admin/flag'
	resources :recommendations, path: 'admin/recommendation'
	resources :evaluations, path: 'admin/evaluation', 
		except: [ :index ]
	resources :consultations, path: 'admin/consultation', 
		only: [ :edit, :update, :destroy ]

 	root 'home_pages#index'	
 
	match '/signup', 				to: 'users#new', 					via: 'get'
	match '/signup',				to: 'users#create',				via: 'post'
	match '/terms_of_use',	to: 'users#terms_of_use', via: 'get'
	match '/terms_of_use',	to: 'users#terms_of_use',	via: 'patch'
	match '/signin',				to: 'sessions#new', 			via: 'get'
	match '/signin', 				to: 'sessions#create', 		via: 'post'
	match '/signout',				to:	'sessions#destroy',		via: 'delete'

	match '/measures', 			to: 'home_pages#measures', 			via: 'get'
 	match '/homeostasis', 	to: 'home_pages#homeostasis', 	via: 'get'
 	match '/science', 			to: 'home_pages#science', 			via: 'get'

	match '/users/:id/profile',	to: 'users#profile',	via: 'get', as: 'profile'
	match '/consultation/:id', to: 'consultations#show', 
		via: 'get', as: 'user_consultation'

	match '/admin', to: 'admin#home', via: 'get'
	match '/admin/orders', to: 'admin#orders', via: 'get'
	match '/admin/users', to: 'admin#users', via: 'get'
	match '/admin/test/:id/evaluate', to: 'tests#evaluate', via: 'post'

  

end

app/models/user.rb
class User < ActiveRecord::Base
	# Relations
	has_many :orders
	has_many :tests
	has_many :results, through: :tests
	has_many :user_recommendations, through: :tests

	# Callbacks
	after_initialize :set_default_role
	before_save { self.email = email.downcase }

	# Validations
	validate :name, presence: true, length: { maximum: 75 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
		uniqueness: { case_sensitive: false }
	
	USER_ROLES = ['normal', 'admin']
	validates :roles, inclusion: { in: USER_ROLES }

	has_secure_password
	validates :password, length: { minimum: 6 }

	# Methods
	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def admin?
		self.roles == 'admin'
	end


	private

		def set_default_role
			unless USER_ROLES.include? self.roles
				self.roles = USER_ROLES[0]
			end
		end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :must_be_signed_in, except: [:new, :create]
	before_action :must_own_resource, 
		except: [:new, :create, :terms_of_use]
	before_action :must_be_signed_out, only: [:new, :create]

	def home
		@user = current_user
	end

	def profile
		@user = current_user
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new user_params

		if @user.save
			sign_in @user
			redirect_to terms_of_use_path

		else
			render :new

		end
	end # create

	def terms_of_use
		@user = current_user

		if params[:user] 
			agreed = params[:user][:terms_of_use]
			
			if agreed == '1'
				if @user.update_attribute :terms_of_use, params[:user][:terms_of_use]
					flash[:notice] = 'Welcome to Measuring Wellness'
					redirect_to root_path

				else
					flash.now[:error] = "We apologize, there was an error. Please try again."	
					render 'terms_of_use'
				end # end update
			
			else
				flash.now[:error] = "Please accept the Terms of Use before continuing"
				render 'terms_of_use'
			end # end agreed
		end # end params[:user]
	end # end terms_of_use

	def show
		@user = User.find params[:id]
	end
	
	def edit
		@user = User.find params[:id]
	end

	def update
		@user = User.find params[:id]
		
		# Only update Profile params
		if params[:submit_profile]
			# Update each attribute individually to avoid validation errors
			# of mass assignment
			user_profile_params.each do |attr, val|
				unless @user.update_attribute( attr, val )
					# Error updating attribute
					flash.now[:error] = 'There was an error updating your profile'
					render 'profile'
					return
				end
			end

			# All attributes updated successfully
			flash[:success] = 'Your profile has been saved'
			redirect_to root_path
			return
		end
				
		if @user.update_attributes user_params
			flash[:success] = 'Your profile has been saved'
			redirect_to root_path

		else
			flash.now[:error] = 'There was an error updating your profile'
			render 'edit'
			
		end
	end

	private

		def user_params
			params.require(:user).permit :name, :email, :password, :password_confirmation,
				:birth_date, :weight, :height, :gender, :terms_of_use
		end

		def user_profile_params
			attrs = params.require(:user).permit :weight, :height, :gender 
			
			year = 		params[:user]['birth_date(1i)'].to_i
			month = 	params[:user]['birth_date(2i)'].to_i
			day = 		params[:user]['birth_date(3i)'].to_i
			attrs[:birth_date] = Date.new( year, month, day ).to_s

			attrs
		end
	
end

app/helpers/users_helper.rb
module UsersHelper
	def admin?
		current_user.admin?
	end

end

app/views/users/_user_attributes_form.html.erb
<%= form_for @user do |f| %>
	<%= render 'shared/form_errors', object: @user %>

	<section class='form-section'>
		<%= f.label :birth_date, 'Date of Birth' %>
		<%= f.date_select :birth_date, start_year: 1900, end_year: Time.now.year %>
	</section>

	<section class='form-section'>
		<%= f.label :weight %>
		<%= f.text_field :weight %> lbs.
	</section>

	<section class='form-section'>
		<%= f.label :height %>
		<%= f.text_field :height %> inches
	</section>

	<section class='form-section'>
		<%= f.label :gender %>
		<%= f.radio_button :gender, 'm' %><%= label_tag 'Male' %>
		<%= f.radio_button :gender, 'f' %><%= label_tag 'Female' %>
	</section>

	<section class='form-section submit-form'>
		<%= f.submit 'Update', name: 'submit_profile' %>
	</section>

<% end %>

app/views/users/_user_form.html.erb
<%= form_for @user do |f| %>
	<%= render 'shared/form_errors', object: f.object %>

	<section class='form-section'>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</section>

	<section class='form-section'>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</section>

	<section class='form-section'>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</section>

	<section class='form-section'>
		<%= f.label :password_confirmation, 'Password Confirmation' %>
		<%= f.password_field :password_confirmation %>
	</section>

	<section class='form-section submit-form'>
		<% submit_label = @user.new_record? ? 'Sign Up' : 'Update' %>
		<%= f.submit submit_label %>
	</section>

<% end %>

app/views/users/edit.html.erb
<h1>Settings</h1>
<div id='basic-settings'>
	<%= render 'user_form' %>
</div>

app/views/users/home.html.erb
<h1><%= @user.name %></h1>
<%= render 'shared/flash' %>

<%= link_to 'Profile', profile_path(@user) %>
<%= link_to 'Order Test', new_order_path %>
<%= link_to 'My Orders', orders_path %>
<%= link_to 'Admin', admin_path if current_user.admin? %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'user_form' %>

app/views/users/profile.html.erb
<h1>My Profile</h1>
<%= render "user_attributes_form" %>

app/views/users/terms_of_use.html.erb
<h1>Terms of Use</h1>
<%= render 'shared/flash' %>

<div style="height: 20em; width: 50em; overflow-y: scroll;">
	<p>
		Measuring Wellness, LLC is a service provider that offers analysis 
			of blood chemistry for wellness monitoring and does not 
			guarantee a state of health. 
		Results provided to you are for informational purposes only and 
			not intended to replace the care of a medical practitioner. 
		We do not diagnose, treat or cure medical conditions. 
		Measuring Wellness, LLC does not replace the care of a medical 
			practitioner or counselor and does not recommend 
			self-diagnosis or self-medication. 
	</p>
	<p>
		There is always a small possibility of an error or failure in 
			laboratory testing. 
		This is inherent to complex testing in any laboratory. 
		Extensive measures are taken to avoid these errors. 
	</p>
	<p>
		Measuring Wellness shall not be liable to you or anyone else 
			for loss or injury caused in whole or part by procuring, 
			compiling, interpreting, delivering, or reporting information 
			through this website. 
		Also, in no event shall Measuring Wellness be held liable to you 
			or anyone else for any decisions made or action taken or not 
			taken by you in reliance on such information. 
	</p>
	<section class='terms'>
		<h2>Terms and Conditions</h2>
		<p>
			By visiting or shopping at this web site, you accept the following terms 
				and conditions. Please read them carefully.
		</p>

		<h3>Copyright</h3>
		<p>
			All content included on this site, such as text, graphics, 
				logos, button icons, images, audio clips, digital downloads, 
				data compilations, and software, is the property of this site's 
				owner or its content suppliers and protected by United States 
				and international copyright laws. 
			The compilation of all content on this site is the exclusive property of 
				this site's owner and protected by U.S. and international copyright laws. 
			All software used on this site is the property of this site's 
				owner or its software suppliers and protected by United States 
				and international copyright laws.
		</p>

		<h3>Disclaimer of Warranties and Limitation of Liability</h3>
		<p>
			THIS SITE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. 
			NO REPRESENTATIONS OR WARRANTIES OF ANY KIND ARE MADE, 
				EXPRESS OR IMPLIED, AS TO THE OPERATION OF THIS SITE OR 
				THE INFORMATION, CONTENT, MATERIALS, OR 
				PRODUCTS INCLUDED ON THIS SITE. 
				YOU EXPRESSLY AGREE THAT YOUR USE OF THIS SITE IS AT YOUR SOLE RISK.
		</p>
		<p>
			TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, 
				THIS SITE'S OWNER DISCLAIMS ALL WARRANTIES, 
				EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, 
				IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
				FOR A PARTICULAR PURPOSE. 
			THIS SITE'S OWNER DOES NOT WARRANT THAT THIS SITE, ITS SERVERS, 
				OR E-MAIL SENT FROM THIS SITE ARE FREE OF VIRUSES 
				OR OTHER HARMFUL COMPONENTS. 
			THIS SITE'S OWNER WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND 
				ARISING FROM THE USE OF THIS SITE, INCLUDING, 
				BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, 
				AND CONSEQUENTIAL DAMAGES.
		</p>
		<p>
			CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES 
				OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. 
			IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, 
				EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, 
				AND YOU MIGHT HAVE ADDITIONAL RIGHTS.
		</p>
		<p>
			While efforts are made to assure that the information provided 
				on the MeasuringWellness.com web site, press releases or 
				any other communication and all its subsidiary pages, 
				is correct and representative or real fact, this site, 
				and all its subsidiary pages, are not explicitly or implicitly 
				warranted or represented to be free of errors, omissions, or inaccuracies.  
				Use the information provided at this site entirely at your own risk.
		</p>
</div>

<%= form_for @user, url: { action: 'terms_of_use' } do |f| %>
	<section class='form-section'>
		<%= f.check_box :terms_of_use %>
		<%= f.label :terms_of_use, 'I agree to the terms of use' %>
	</section>

	<section class='form-section submit-form'>
		<%= f.submit 'Submit' %>
	</section>

<% end %>