config/routes.rb
MeasuringWellness::Application.routes.draw do
	resources :users
	resources :sessions, only: [ :new, :create, :destroy ]
	resources :orders
	resources :recommendations, except: [ :new ]	

	resources :coupons, only: [ :new, :create, :destroy ], path: '/admin/coupon'
	resources :analytes, path: '/admin/analyte'
	resources :analyte_groups, path: '/admin/analyte_group'
	resources :rules, path: '/admin/rule'
	resources :thresholds, path: '/admin/threshold'
	resources :results, path: '/admin/result'
	resources :tests, path: '/admin/test'
	
	resources :flags, path: '/admin/flag'
	resources :recommendations, path: 'admin/recommendation'
	resources :evaluations, path: 'admin/evaluation', 
		except: [ :index ]
	resources :consultations, path: 'admin/consultation', 
		only: [ :edit, :update, :destroy ]

 	root 'home_pages#index'	
 
	match '/signup', 				to: 'users#new', 					via: 'get'
	match '/signup',				to: 'users#create',				via: 'post'
	match '/terms_of_use',	to: 'users#terms_of_use', via: 'get'
	match '/terms_of_use',	to: 'users#terms_of_use',	via: 'patch'
	match '/signin',				to: 'sessions#new', 			via: 'get'
	match '/signin', 				to: 'sessions#create', 		via: 'post'
	match '/signout',				to:	'sessions#destroy',		via: 'delete'

	match '/measures', 			to: 'home_pages#measures', 			via: 'get'
 	match '/homeostasis', 	to: 'home_pages#homeostasis', 	via: 'get'
 	match '/science', 			to: 'home_pages#science', 			via: 'get'

	match '/users/:id/profile',	to: 'users#profile',	via: 'get', as: 'profile'
	match '/consultation/:id', to: 'consultations#show', 
		via: 'get', as: 'user_consultation'

	match '/admin', to: 'admin#home', via: 'get'
	match '/admin/orders', to: 'admin#orders', via: 'get'
	match '/admin/users', to: 'admin#users', via: 'get'
	match '/admin/test/:id/evaluate', to: 'tests#evaluate', via: 'post'

  

end

app/models/result.rb
class Result < ActiveRecord::Base
	# Callbacks
	

	# Relations
	belongs_to :analyte
	belongs_to :test

	# Validations
	validates :amount, presence: true

	def test
		Test.find self.test_id
	end

	def get_group_severity
		self
	end	

	def get_analyte_severity
		analyte = self.analyte
		partition = analyte.partitions.get_amount_partition self.amount
		partition.severity
	end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
	before_action :must_be_admin

	def index
		@results = Result.all
	end

	def show
		@result = Result.find params[:id]
	end

=begin
	def new
		@result = Result.new
		
		@tests = tests_for_select
		@default_test = params[:default_test]
		
		@analytes = analytes_for_select
		@default_analyte = params[:default_analyte] 
	end

	def create
		@result = Result.new result_params
	end

	def edit
		@result = Result.find params[:id]
		@analyte = @result.analyte
		@test = @result.test
		@order = @test.order
		@user = @test.user
	end

	def update
		@result = Result.find params[:id]
		
		if @result.update_attributes( result_params )
			flash[:success] = "Result updated!"
			redirect_to result_path( @result )

		else
			flash.now[:error] = "The Result could not be updated"
			render :edit

		end
	end
=end

	def destroy
		result = Result.find params[:id]
		test = result.test
		result.destroy

		flash[:success] = "Result removed"
		redirect_to test_path( test )
	end

	private

		def result_params
			#params.require( :result ).permit :amount
		end

		def tests_for_select
			tests = Test.all
			arr = []
			tests.each do |t|
				arr << [ "#{t.user.name} - #{t.id}", t.id ]
			end

			arr.sort! { |x, y| x[0] <=> y[0] }
		end

		def analytes_for_select
			analytes = Analyte.all
			arr = []
			analytes.each do |a|
				arr << [ a.name, a.id ]
			end

			arr.sort! { |x, y| x[0] <=> y[0] }
		end

end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/results/_result_form.html.erb
<%= form_tag controller: :results, 
	action: ( @result.new_record? ? :create : :update ) do |f| %>
		
		<%= label_tag :test %>
	<%= select_tag :test, options_for_select( @tests, @default_test ) %>

	<%= label_tag :analyte %>
	<%= select_tag :analyte, options_for_select( @analytes, @default_analyte ) %>

	<%= label_tag :amount %>
	<%= text_field_tag :amount %>

	<%= submit_tag "Save Result" %>
<% end %>

app/views/results/edit.html.erb
<h1>Edit Result</h1>
<%= render 'shared/flash' %>

<h2><%= @user.name %></h2>
<h3>Order <%= @order.id %> | <%= @order.created_at %></h3>

<%= form_for @result do |f| %>
	<%= f.label :amount, @analyte.name %>
	<%= f.text_field :amount %>

	<%= f.submit %>
<% end %>

<%= link_to 'Cancel', result_path( @result ) %>

app/views/results/index.html.erb
<h1>Results</h1>
<%= link_to "Admin", admin_path %>
<%= render 'shared/flash' %>

<%#= link_to 'Add Result', new_result_path %>
<table>
	<thead>
		<th>User</th>
		<th>Test</th>
		<th>Analyte</th>
		<th>Amount</th>
	</thead>
	<tbody>
		<% @results.each do |result| %>
			<tr>
				<td><%= result.test.user.name %></td>
				<td><%= result.test.id %></td>
				<td><%= result.analyte.name %></td>
				<td><%= result.amount %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/results/new.html.erb
<h1>New Result</h1>
<%= render 'shared/flash' %>

<%= render partial: 'result_form' %>

<%= link_to "Cancel", results_path %>